# Generated by Django 4.0.2 on 2022-02-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_transacao_obs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='desc',
            new_name='descrição',
        ),
    ]
