# Generated by Django 4.0.2 on 2022-02-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_rename_desc_transacao_descrição'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
